### ISSUE TITLE
End game tracking 

### ISSUE THREAD

**Issue by lovelyyfiaaa** [waylovely-project/waylovely#1]
Hii ^^

This is the lovely end-game tracking issue for Waylovely. 😊

Here's a lovely progress report/devblog thread! https://twitter.com/lovelyy_fiaa/status/1537964829444820993

- [x] Make Anvil and Smithay pass `cargo check` on `x86_64-linux-android`  
  - [x] Disable non-winit backends 
  - [x] Switch to an alternative of memfd, since it's not available on Bionic libc (done by 9d41e3b94d707d0c5b234bd650eee234d403b0d5)
  - [x] Implement the backend for Android (done by e4bfc4fa8d3ea3b2785d857450a73871d73ef6d2)
- [x] Implement packaging
  - [x] waylovely-project/smithay#2
  - [x] Package them in an Apk!
- [x] Running Waylovely on real Android device
 
Issues we encounter during QA:
- [x] Xkbcommon needs the lovely X11 folder path
    - [x] pass `$cache/x11` to the configuration
    - Copy the x11 resources from the APK to the cache folder at first run 
    - [ ] Create a good bindings library for the SDK to do that!! See waylovely-project/arabica

Then we can ship a Proof of Concept app with the GTK and Libadwaita demo!
Then we need to make this production ready! The tracking are:
- [x] Make the compositor a library that can be shared by apps! (since Waylovely and its dependencies should  be quite big ☺️)
- [ ] Perhaps make an app that allows people to install apps from Flatpak? Soo the idea is that with this, people can run desktop apps in Android "natively"!
